baseURL = "https://andikadinata.tech"
languageCode = "id-ID"
title = "Andika Dinata's blog."
author = "Andika Dinata"
theme = "paper"

[params]
color = "light"
math = true
github = "thepastlife"
instagram = "andikadinata.x"

[pagination]
pagerSize = 10

[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 10

[params.giscus]
repo = "thepastlife/blog"
repoId = "R_kgDOPdIO7g"
category = "General"
categoryId = "DIC_kwDOPdIO7s4CuHsy"
mapping = "url"
lang = "en"
reactions-enabled = "1"
input-position = "top"
loading = "lazy"
